language: php
sudo: false

php:
  - '5.6'
  - '7.0'

env:
  - TESTBENCH_VERSION=3.1.*
  - TESTBENCH_VERSION=3.2.*
  - TESTBENCH_VERSION=3.3.*@dev

cache:
  directories:
  - $HOME/.composer/cache

before_script:
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - travis_retry composer update --dev --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit