language: php
sudo: false

env:
  - TESTBENCH_VERSION=3.2.*

cache:
  directories:
  - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5.9
      env: TESTBENCH_VERSION=3.1.*
    - php: 5.5.9
      env: TESTBENCH_VERSION=3.3.*@dev
    - php: 5.6
      env: TESTBENCH_VERSION=3.1.*
    - php: 5.6
      env: TESTBENCH_VERSION=3.3.*@dev
    - php: 7.0
      env: TESTBENCH_VERSION=3.1.*
    - php: 7.0
      env: TESTBENCH_VERSION=3.3.*@dev

before_script:
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - travis_retry composer update --dev --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit